version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/medflick2
    overwrite: true
file_exists_behavior: OVERWRITE



hooks:
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 600
